apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-tap-dev
  namespace: sandbox-example
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: tanzu
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 80Gi
      tkr:  
        reference:
          name: v1.21.6---vmware.1-tkg.1.b3d708a
    nodePools:
    - name: worker-nodepool-a1
      replicas: 3
      vmClass: best-effort-xlarge
      storageClass: tanzu
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 120Gi
      tkr:  
        reference:
          name: v1.21.6---vmware.1-tkg.1.b3d708a
  settings:
    storage:
      defaultClass: tanzu
